In [50]:
import numpy as np
import pandas as pd

In [51]:
#Loading the Dataset file.
df = pd.read_csv("student_scores.csv")

In [52]:
df

,Student_ID,Study_Hours,Attendance_Percentage,Sleep_Hours,Previous_Score,Score
0,1,1.0,60,5.0,8,10.0
1,2,1.5,62,5.5,12,16.0
2,3,2.0,65,6.0,18,21.0
3,4,2.5,68,6.0,22,26.0
4,5,3.0,70,6.5,28,32.0
5,6,3.5,72,7.0,33,37.0
6,7,4.0,75,7.0,38,43.0
7,8,4.5,78,7.5,44,49.0
8,9,5.0,80,7.5,49,54.0
9,10,5.5,82,8.0,53,58.0
10,11,6.0,85,8.0,60,NaN
11,12,6.5,86,8.0,63,69.0
12,13,7.0,88,8.5,70,75.0
13,14,7.5,90,8.5,74,80.0
14,15,8.0,92,9.0,80,86.0
15,16,8.5,93,9.0,85,NaN
16,17,9.0,95,9.0,89,94.0
17,18,9.5,97,9.5,93,97.0
18,19,2.0,65,6.0,18,21.0
19,20,5.0,80,7.5,49,54.0

In [53]:
df.shape

(20, 6)

In [54]:
# It shows the first 5 rows.
df.head()

,Student_ID,Study_Hours,Attendance_Percentage,Sleep_Hours,Previous_Score,Score
0,1,1.0,60,5.0,8,10.0
1,2,1.5,62,5.5,12,16.0
2,3,2.0,65,6.0,18,21.0
3,4,2.5,68,6.0,22,26.0
4,5,3.0,70,6.5,28,32.0

In [55]:
# Checking all the null values.
#True means it has Null value.
df.isna()

,Student_ID,Study_Hours,Attendance_Percentage,Sleep_Hours,Previous_Score,Score
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,True
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,True
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False

In [56]:
df.isnull().sum()

Student_ID               0
Study_Hours              0
Attendance_Percentage    0
Sleep_Hours              0
Previous_Score           0
Score                    2
dtype: int64

In [57]:
df.loc[2,'Score']

np.float64(21.0)

In [58]:
#If null value is filled by mean.
#Method-1
df['Score'] = df['Score'].fillna(df['Score'].mean())

In [59]:
df

,Student_ID,Study_Hours,Attendance_Percentage,Sleep_Hours,Previous_Score,Score
0,1,1.0,60,5.0,8,10.000000
1,2,1.5,62,5.5,12,16.000000
2,3,2.0,65,6.0,18,21.000000
3,4,2.5,68,6.0,22,26.000000
4,5,3.0,70,6.5,28,32.000000
5,6,3.5,72,7.0,33,37.000000
6,7,4.0,75,7.0,38,43.000000
7,8,4.5,78,7.5,44,49.000000
8,9,5.0,80,7.5,49,54.000000
9,10,5.5,82,8.0,53,58.000000
10,11,6.0,85,8.0,60,51.222222
11,12,6.5,86,8.0,63,69.000000
12,13,7.0,88,8.5,70,75.000000
13,14,7.5,90,8.5,74,80.000000
14,15,8.0,92,9.0,80,86.000000
15,16,8.5,93,9.0,85,51.222222
16,17,9.0,95,9.0,89,94.000000
17,18,9.5,97,9.5,93,97.000000
18,19,2.0,65,6.0,18,21.000000
19,20,5.0,80,7.5,49,54.000000

In [60]:
#Method-2
df.fillna(df.mean(numeric_only=True))

,Student_ID,Study_Hours,Attendance_Percentage,Sleep_Hours,Previous_Score,Score
0,1,1.0,60,5.0,8,10.000000
1,2,1.5,62,5.5,12,16.000000
2,3,2.0,65,6.0,18,21.000000
3,4,2.5,68,6.0,22,26.000000
4,5,3.0,70,6.5,28,32.000000
5,6,3.5,72,7.0,33,37.000000
6,7,4.0,75,7.0,38,43.000000
7,8,4.5,78,7.5,44,49.000000
8,9,5.0,80,7.5,49,54.000000
9,10,5.5,82,8.0,53,58.000000
10,11,6.0,85,8.0,60,51.222222
11,12,6.5,86,8.0,63,69.000000
12,13,7.0,88,8.5,70,75.000000
13,14,7.5,90,8.5,74,80.000000
14,15,8.0,92,9.0,80,86.000000
15,16,8.5,93,9.0,85,51.222222
16,17,9.0,95,9.0,89,94.000000
17,18,9.5,97,9.5,93,97.000000
18,19,2.0,65,6.0,18,21.000000
19,20,5.0,80,7.5,49,54.000000

In [61]:
# Null value ki rows drop ho jaayegi.
df.dropna()

,Student_ID,Study_Hours,Attendance_Percentage,Sleep_Hours,Previous_Score,Score
0,1,1.0,60,5.0,8,10.000000
1,2,1.5,62,5.5,12,16.000000
2,3,2.0,65,6.0,18,21.000000
3,4,2.5,68,6.0,22,26.000000
4,5,3.0,70,6.5,28,32.000000
5,6,3.5,72,7.0,33,37.000000
6,7,4.0,75,7.0,38,43.000000
7,8,4.5,78,7.5,44,49.000000
8,9,5.0,80,7.5,49,54.000000
9,10,5.5,82,8.0,53,58.000000
10,11,6.0,85,8.0,60,51.222222
11,12,6.5,86,8.0,63,69.000000
12,13,7.0,88,8.5,70,75.000000
13,14,7.5,90,8.5,74,80.000000
14,15,8.0,92,9.0,80,86.000000
15,16,8.5,93,9.0,85,51.222222
16,17,9.0,95,9.0,89,94.000000
17,18,9.5,97,9.5,93,97.000000
18,19,2.0,65,6.0,18,21.000000
19,20,5.0,80,7.5,49,54.000000

In [62]:
# To count exact duplicate rows.
df.duplicated().sum()

np.int64(0)

In [63]:
df.describe()

,Student_ID,Study_Hours,Attendance_Percentage,Sleep_Hours,Previous_Score,Score
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,10.50000,5.075000,79.150000,7.450000,49.300000,51.222222
std,5.91608,2.627161,11.590718,1.296757,26.885919,26.110203
min,1.00000,1.000000,60.000000,5.000000,8.000000,10.000000
25%,5.75000,2.875000,69.500000,6.375000,26.500000,30.500000
50%,10.50000,5.000000,80.000000,7.500000,49.000000,51.222222
75%,15.25000,7.125000,88.500000,8.500000,71.000000,70.500000
max,20.00000,9.500000,97.000000,9.500000,93.000000,97.000000

In [64]:
df['Score'].median()

51.22222222222222

In [65]:
df['Study_Hours'].std()

2.627160764820175

In [66]:
df['Score'] = df['Score'].astype(float)
df

,Student_ID,Study_Hours,Attendance_Percentage,Sleep_Hours,Previous_Score,Score
0,1,1.0,60,5.0,8,10.000000
1,2,1.5,62,5.5,12,16.000000
2,3,2.0,65,6.0,18,21.000000
3,4,2.5,68,6.0,22,26.000000
4,5,3.0,70,6.5,28,32.000000
5,6,3.5,72,7.0,33,37.000000
6,7,4.0,75,7.0,38,43.000000
7,8,4.5,78,7.5,44,49.000000
8,9,5.0,80,7.5,49,54.000000
9,10,5.5,82,8.0,53,58.000000
10,11,6.0,85,8.0,60,51.222222
11,12,6.5,86,8.0,63,69.000000
12,13,7.0,88,8.5,70,75.000000
13,14,7.5,90,8.5,74,80.000000
14,15,8.0,92,9.0,80,86.000000
15,16,8.5,93,9.0,85,51.222222
16,17,9.0,95,9.0,89,94.000000
17,18,9.5,97,9.5,93,97.000000
18,19,2.0,65,6.0,18,21.000000
19,20,5.0,80,7.5,49,54.000000

In [67]:
# Saving the cleaned version:
df.to_csv("student_scores_cleaned.csv", index=False)